### ISSUE TITLE
Hello, Welcome!

### ISSUE THREAD

**Issue by ChishFoxcat** [WOLFRAZOR/my-personal-situation#1]
### Welcome to join the Github!
- My name is `Chish` . You can go to [my Github pages](https://github.com/ChishFoxcat) to learn about me.
- Github's help pages will help you find all kinds of questions and solutions.
- Self-introduction page can do this. **Look down**
> 1. Create a project with you with your username, for example: `WOLFRAZOR/WOLFRAZOR`
> 2. Then you can edit the `README.md` directly, or use Github's softwares Clone warehouse for local IDE editing.
### Thank you for read this.If you don't understand, you can contact me privately.

**Comment by WOLFRAZOR** [comment]
### OK！I will try to do it follow your guide! **I had try to read Github official docs, but failed. Here is the note: 我们经常发布文档更新，此页面的翻译可能仍在进行中。有关最新信息，请访问英文文档。如果此页面上的翻译有问题，请告诉我们。**

Some Chinese translate is wrong (一些地方翻译没有错误，但有歧义）。Maybe I should learn about the ### professional English(专业英语）.

Recently, My **College Entrance Exam(高考）failed.** Now I am studying the Korea（此处指韩语） Preparatory course（预科）in **SISU（上海外国语大学。分松江校区和虹口校区。虹口校区为老校区、位于大连西路550号，离地铁3号线赤峰路站很近。松江校区为新校区，位于文翔路1550号，离地铁9号线松江大学城站近，文汇路校门旁边就是松江有轨电车2号线站点——文汇路站）(文翔路和大连西路的校门都为正门）**

I believe you should have seen my news in coolapk . **I don't want talk more in here.**

There is a difference between Korean preparatory course and English preparatory course. **IELTS tests not only English (but also mathematics ,Physics, biology and chemistry), but Korean preparatory course only tests Korean (TOPIK)**

Everyday, I'm busy in class（Monday to Friday morning). Reading in the morning and grammar in the afternoon（早上上的课叫泛读，extensive reading。下午上的是精读，intensive reading。也可以叫阅读和语法。）

**Comment by WOLFRAZOR** [comment]
The recent things to do **are as follows**

1. Less open QQ and wechat，not open zhihu、weibo、tieba、Sina. _Is there no pure land on the Internet?（Global include China）（How about the situation in CSDN community? I don't know.)_
2. Play less Genshin Impact.（Because the equipment I use is MI 6，I install **the Cloud game** version instead of the normal version. **Every day you log in, you have 15 minutes of free time.There are five servers: West China, central China, East China, South China and North China.华西、华中、华东、华南、华北**）_（小米6永不为奴！835永不为奴！）_
3. Work hard in the Korea Study._【如果见到朝鲜语（韩国），请不要惊慌。这是历史原因导致的。韩语和朝鲜语在部分单词仍然有区别。这里的Korea指的是韩语。如果我不说明，可能会引发歧义和误会。】_

**Comment by WOLFRAZOR** [comment]
> ## 👋Hello!
> ### Welcome to join the Github!
> * My name is `Chish` . You can go to [my Github pages](https://github.com/ChishFoxcat) to learn about me.
> * Github's help pages will help you find all kinds of questions and solutions.
> * Self-introduction page can do this. **Look down**
> 
> > 1. Create a project with you with your username, for example: `WOLFRAZOR/WOLFRAZOR`
> > 2. Then you can edit the `README.md` directly, or use Github's softwares Clone warehouse for local IDE editing.
> 
> #### You can refer to the warehouse for **`Fork`** my self-introduction.
> ### Thank you for read this.If you don't understand, you can contact me privately.

_My MacBook Pro's Butterfly keyboard is close to scrapping.Those that have been scrapped include：Z, X, left option , M键右边的逗号，left shift._（写到这里才发现，我之前发的都忘了加回复标签。好尴尬的局面。）

**Comment by WOLFRAZOR** [comment]
> ## 👋Hello!
> ### Welcome to join the Github!
> * My name is `Chish` . You can go to [my Github pages](https://github.com/ChishFoxcat) to learn about me.
> * Github's help pages will help you find all kinds of questions and solutions.
> * Self-introduction page can do this. **Look down**
> 
> > 1. Create a project with you with your username, for example: `WOLFRAZOR/WOLFRAZOR`
> > 2. Then you can edit the `README.md` directly, or use Github's softwares Clone warehouse for local IDE editing.
> 
> #### You can refer to the warehouse for **`Fork`** my self-introduction.
> ### Thank you for read this.If you don't understand, you can contact me privately.

OK！I will try to do it follow your guide! I had try to read Github official docs, but failed. Here is the note: 我们经常发布文档更新，此页面的翻译可能仍在进行中。有关最新信息，请访问英文文档。如果此页面上的翻译有问题，请告诉我们。

Some Chinese translate is wrong (一些地方翻译没有错误，但有歧义）。Maybe I should learn about the ### professional English(专业英语）.

Recently, My College Entrance Exam(高考）failed. Now I am studying the Korea（此处指韩语） Preparatory course（预科）in SISU（上海外国语大学。分松江校区和虹口校区。虹口校区为老校区、位于大连西路550号，离地铁3号线赤峰路站很近。松江校区为新校区，位于文翔路1550号，离地铁9号线松江大学城站近，文汇路校门旁边就是松江有轨电车2号线站点——文汇路站）(文翔路和大连西路的校门都为正门）

I believe you should have seen my news in coolapk . I don't want talk more in here.

There is a difference between Korean preparatory course and English preparatory course. IELTS tests not only English (but also mathematics ,Physics, biology and chemistry), but Korean preparatory course only tests Korean (TOPIK)

Everyday, I'm busy in class（Monday to Friday morning). Reading in the morning and grammar in the afternoon（早上上的课叫泛读，extensive reading。下午上的是精读，intensive reading。也可以叫阅读和语法。）

**Comment by WOLFRAZOR** [comment]
> ## 👋Hello!
> ### Welcome to join the Github!
> * My name is `Chish` . You can go to [my Github pages](https://github.com/ChishFoxcat) to learn about me.
> * Github's help pages will help you find all kinds of questions and solutions.
> * Self-introduction page can do this. **Look down**
> 
> > 1. Create a project with you with your username, for example: `WOLFRAZOR/WOLFRAZOR`
> > 2. Then you can edit the `README.md` directly, or use Github's softwares Clone warehouse for local IDE editing.
> 
> #### You can refer to the warehouse for **`Fork`** my self-introduction.
> ### Thank you for read this.If you don't understand, you can contact me privately.

The issue you wrote Some code I'm not familiar with it. It's hard to understand.（毕竟是刚入坑的。还正在熟悉中。请大佬谅解。）

**Comment by WOLFRAZOR** [comment]
> ## 👋Hello!
> ### Welcome to join the Github!
> * My name is `Chish` . You can go to [my Github pages](https://github.com/ChishFoxcat) to learn about me.
> * Github's help pages will help you find all kinds of questions and solutions.
> * Self-introduction page can do this. **Look down**
> 
> > 1. Create a project with you with your username, for example: `WOLFRAZOR/WOLFRAZOR`
> > 2. Then you can edit the `README.md` directly, or use Github's softwares Clone warehouse for local IDE editing.
> 
> #### You can refer to the warehouse for **`Fork`** my self-introduction.
> ### Thank you for read this.If you don't understand, you can contact me privately.

The recent things to do are as follows

Less open QQ and wechat，not open zhihu、weibo、tieba、Sina. Is there no pure land on the Internet?（Global include China）（How about the situation in CSDN community? I don't know.)
Play less Genshin Impact.（Because the equipment I use is MI 6，I install the Cloud game version instead of the normal version. Every day you log in, you have 15 minutes of free time.There are five servers: West China, central China, East China, South China and North China.华西、华中、华东、华南、华北）（小米6永不为奴！835永不为奴！）
Work hard in the Korea Study.【如果见到朝鲜语（韩国），请不要惊慌。这是历史原因导致的。韩语和朝鲜语在部分单词仍然有区别。这里的Korea指的是韩语。如果我不说明，可能会引发歧义和误会。】

**Comment by WOLFRAZOR** [comment]
> ## 👋Hello!
> ### Welcome to join the Github!
> * My name is `Chish` . You can go to [my Github pages](https://github.com/ChishFoxcat) to learn about me.
> * Github's help pages will help you find all kinds of questions and solutions.
> * Self-introduction page can do this. **Look down**
> 
> > 1. Create a project with you with your username, for example: `WOLFRAZOR/WOLFRAZOR`
> > 2. Then you can edit the `README.md` directly, or use Github's softwares Clone warehouse for local IDE editing.
> 
> #### You can refer to the warehouse for **`Fork`** my self-introduction.
> ### Thank you for read this.If you don't understand, you can contact me privately.

大部分回复我还是会用英语写。用中文的情况，要么是英语表达不出来或者需要进行注释。

**Comment by WOLFRAZOR** [comment]
> ## 👋Hello!
> ### Welcome to join the Github!
> * My name is `Chish` . You can go to [my Github pages](https://github.com/ChishFoxcat) to learn about me.
> * Github's help pages will help you find all kinds of questions and solutions.
> * Self-introduction page can do this. **Look down**
> 
> > 1. Create a project with you with your username, for example: `WOLFRAZOR/WOLFRAZOR`
> > 2. Then you can edit the `README.md` directly, or use Github's softwares Clone warehouse for local IDE editing.
> 
> #### You can refer to the warehouse for **`Fork`** my self-introduction.
> ### Thank you for read this.If you don't understand, you can contact me privately.

**_For a person who has no programming foundation (actually lost), it takes a long time to use GitHub.Sorry for my poor English._**

**Comment by WOLFRAZOR** [comment]
> ## 👋Hello!
> ### Welcome to join the Github!
> * My name is `Chish` . You can go to [my Github pages](https://github.com/ChishFoxcat) to learn about me.
> * Github's help pages will help you find all kinds of questions and solutions.
> * Self-introduction page can do this. **Look down**
> 
> > 1. Create a project with you with your username, for example: `WOLFRAZOR/WOLFRAZOR`
> > 2. Then you can edit the `README.md` directly, or use Github's softwares Clone warehouse for local IDE editing.
> 
> #### You can refer to the warehouse for **`Fork`** my self-introduction.
> ### Thank you for read this.If you don't understand, you can contact me privately.

### :(

**Comment by WOLFRAZOR** [comment]
> ## 👋Hello!
> ### Welcome to join the Github!
> * My name is `Chish` . You can go to [my Github pages](https://github.com/ChishFoxcat) to learn about me.
> * Github's help pages will help you find all kinds of questions and solutions.
> * Self-introduction page can do this. **Look down**
> 
> > 1. Create a project with you with your username, for example: `WOLFRAZOR/WOLFRAZOR`
> > 2. Then you can edit the `README.md` directly, or use Github's softwares Clone warehouse for local IDE editing.
> 
> #### You can refer to the warehouse for **`Fork`** my self-introduction.
> ### Thank you for read this.If you don't understand, you can contact me privately.

mogul，don't angry with me.

**Comment by WOLFRAZOR** [comment]
> ## 👋Hello!
> ### Welcome to join the Github!
> * My name is `Chish` . You can go to [my Github pages](https://github.com/ChishFoxcat) to learn about me.
> * Github's help pages will help you find all kinds of questions and solutions.
> * Self-introduction page can do this. **Look down**
> 
> > 1. Create a project with you with your username, for example: `WOLFRAZOR/WOLFRAZOR`
> > 2. Then you can edit the `README.md` directly, or use Github's softwares Clone warehouse for local IDE editing.
> 
> #### You can refer to the warehouse for **`Fork`** my self-introduction.
> ### Thank you for read this.If you don't understand, you can contact me privately.

**_VPN这个问题是非常严重的。搞不好可能会出事。用这货真的要提心吊胆。_**

**Comment by WOLFRAZOR** [comment]
> ## 👋Hello!
> ### Welcome to join the Github!
> * My name is `Chish` . You can go to [my Github pages](https://github.com/ChishFoxcat) to learn about me.
> * Github's help pages will help you find all kinds of questions and solutions.
> * Self-introduction page can do this. **Look down**
> 
> > 1. Create a project with you with your username, for example: `WOLFRAZOR/WOLFRAZOR`
> > 2. Then you can edit the `README.md` directly, or use Github's softwares Clone warehouse for local IDE editing.
> 
> #### You can refer to the warehouse for **`Fork`** my self-introduction.
> ### Thank you for read this.If you don't understand, you can contact me privately.

The problem is **Your GitHub account  is Pro , but. my GitHub account is free.(因为我的学生证并不属于体制内的统招，所以学生优惠并不能使用。只能原价购买。有一些功能确实需要付费才能使用。）付费是只能通过Paypal或者汇款吗？**

**hope you reply when you have the free time.**

**Comment by ChishFoxcat** [comment]
OK, thanks for you read this.
- 确实付款只能使用外商卡或者Palpay

I wish you a happy life!😊
```
You can search for related Markdown syntax in Google or Bing. 
It is impossible to cite any html in Github. This is a backward thing.
```

**Comment by WOLFRAZOR** [comment]
> OK, thanks for you read this.
> 
> * 确实付款只能使用外商卡或者Palpay
> 
> I wish you a happy life!😊
> 
> ```
> You can search for related Markdown syntax in Google or Bing. 
> It is impossible to cite any html in Github. This is a backward thing.
> ```

I want to ask a question,**How to Implemented in code：（效果如下。题目要求是用”*、+、-、/“四个运算符将两行字符串包围。光是搞一排”*“和“/”就花了很多时间。网上打星号打出的是图形，没法打单排。）**
*****************

+ Hello Python     -
+ I   love python   -
///////////////////////////

_(好家伙，那书用的还是eclipse。jetbrains的pycharm和vsc不比它好用？）_

**Comment by WOLFRAZOR** [comment]
> OK, thanks for you read this.
> 
> * 确实付款只能使用外商卡或者Palpay
> 
> I wish you a happy life!😊
> 
> ```
> You can search for related Markdown syntax in Google or Bing. 
> It is impossible to cite any html in Github. This is a backward thing.
> ```

`*******************
+ Hello Python    -
+ I  love python   -
///////////////////////////////`

**Comment by WOLFRAZOR** [comment]
> OK, thanks for you read this.
> 
> * 确实付款只能使用外商卡或者Palpay
> 
> I wish you a happy life!😊
> 
> ```
> You can search for related Markdown syntax in Google or Bing. 
> It is impossible to cite any html in Github. This is a backward thing.
> ```

**星号被折叠了。所以重新打一次。第二句话是右边偏移一点的（发出来却给我自动对齐了。:(    “+”、“-”对齐。**
